name: Integration
on:
  push:
  pull_request:
    branches:
      - master
      - develop
      
jobs:
  run-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: |
          npm install
          npm install -g @angular/cli@14.2.12
      - name: Run tests
        run: |
          npm run test:coverage